# Remote theme directory
remote_theme: sainikhith/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-feed

#-------------------------------
# General Site Settings
title: Darren Smith
description: "I have a long-standing passion for computing technology. Due to this passion, I have always been technical, and creative and studied a (Msc) Advanced Multimedia and 3D Technologies at Brunel University I am fascinated by Data, machine learning, and computer games and am currently seeking placement in the industry to utilise my skills and add to my experience"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://darrensmith10.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
author: "Darren Smith"

#-------------------------------
# About Section
subtitle: Data Analyst and Software Developer <span style="color:#f58506"> Portfolio </span>
location: "Surrey, UK"
cv_url: "docs/Darren_Smith_CV_1st_May_2025.pdf" # Add your CV URL
avatar_image: img/DarrenNewProfile.jpg

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/darren-smith-9b89b95b/" # Add your linkedln handle
github: "https://github.com/DarrenSmith10"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false

include:
  - assets/css/custom.css
#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
# Include custom CSS file


